#!/bin/bash

# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2025 Emanuel Strobel
# bypassing dreambox direct SDCARD boot options to LibreElec *box.img

MODEL=${1}
BOX="dreambox-${MODEL}"
BOOT_TYPE=${2}
BOARD="g12b"
BOOTLOADER="uboot_dream${MODEL}.bin"
BOOTLOADER_EXT="u-boot_s922x.bin"
BOOTSCR="autoexec.img"
CUSTOM_DTB="echo no custom device-tree"

# optional or ""
DEBUG="no_console_suspend debugging"

if [ "${MODEL}" == "play" ]; then
    BOARD="g12a"
    BOOT_TYPE=""
    BOOTLOADER_EXT="u-boot-s905x2.bin"
    BOOTSCR="aml_autoscript.scr"
    #CUSTOM_DTB="sudo cp extboot/custom_dtb/*${BOARD}-${BOX}.dtb LE_BOOT/amlogic"
fi

DTB="meson-${BOARD}-${BOX}.dtb"
IMG="${BOX}.img"
BOOTSCR_NAME=${BOOTSCR}

if [ "${BOOT_TYPE}" == "gpt" ]; then
    BOOTLOADER="u-boot.bin.encrypt"
    BOOTSCR="autoexec_gpt.img"
    IMG="${BOX}_gpt-multiboot.img"
fi

if [ "${BOOT_TYPE}" == "multi" ]; then
    BOOTLOADER=""
    IMG="${BOX}_multiboot.img"
fi

sudo echo || exit 1

echo "[$(basename ${0})] packing ${IMG}..."

pigz -fdk LibreELEC-AMLGX.a*-box.img.gz || exit 1

mkdir LE_BOOT

START=`sudo fdisk -l LibreELEC-AMLGX.a*-box.img | grep .img1 | awk -e '{ print $3 }'`
OFFSET=$(expr 512 '*' $START)
LOOPDEV=$(losetup -f)

sudo losetup -o $OFFSET $LOOPDEV LibreELEC-AMLGX.a*-box.img
sudo mount -rw $LOOPDEV LE_BOOT

if [ "${MODEL}" != "play" ] && [ "${BOOT_TYPE}" != "multi" ]; then
    sudo dosfslabel $LOOPDEV "DREAMBOOT"
fi

sudo cp -r extboot/${BOOTSCR} LE_BOOT/${BOOTSCR_NAME}
sudo cp -r extboot/${BOOTLOADER_EXT} LE_BOOT/u-boot.ext
$(CUSTOM_DTB)

sudo sed -i "s!@@DTB_NAME@@!$DTB!" LE_BOOT/uEnv.ini

if [ "${DEBUG}" != "" ]; then
    BOOT_ARGS=`cat LE_BOOT/uEnv.ini | grep bootargs | sed -e 's/ quiet//'`
    BOOT_ARGS="$BOOT_ARGS ${DEBUG}"
    sudo sed -i "s!bootargs.*!$BOOT_ARGS!" LE_BOOT/uEnv.ini
fi

echo "[$(basename ${0})] uEnv.ini:"
cat  LE_BOOT/uEnv.ini
echo
echo "[$(basename ${0})] boot partition:"
ls LE_BOOT
echo "[$(basename ${0})] boot partition /amlogic:"
ls LE_BOOT/amlogic
echo

sync
sudo umount LE_BOOT
sudo losetup -d $LOOPDEV
sudo rmdir LE_BOOT

if [ "${MODEL}" != "play" ] && [ "${BOOT_TYPE}" != "multi" ]; then
    mkdir LE_ROOT
    START=`sudo fdisk -l LibreELEC-AMLGX.a*-box.img | grep .img2 | awk -e '{ print $2 }'`
    OFFSET=$(expr 512 '*' $START)
    LOOPDEV=$(losetup -f)

    sudo losetup -o $OFFSET $LOOPDEV LibreELEC-AMLGX.a*-box.img
    sudo mount -rw $LOOPDEV LE_ROOT

    sudo cp -r storage/bin LE_ROOT
    sudo cp -r storage/.config LE_ROOT
    sudo cp -r storage/.profile LE_ROOT

    echo "[$(basename ${0})] storage partition:"
    ls -a LE_ROOT/
    echo

    sync
    sudo umount -l LE_ROOT
    sleep 1
    sudo losetup -d $LOOPDEV
    sleep 1
    sudo rmdir LE_ROOT
fi

NAME=`ls LibreELEC-AMLGX.a*-box.img | sed -e 's/box.img//'`${IMG}
mv `ls LibreELEC-AMLGX.a*-box.img` ${NAME}

if [ "${BOOTLOADER}" != "" ]; then
    dd if=extboot/${BOOTLOADER} of="${NAME}" conv=fsync,notrunc bs=1 count=440
    dd if=extboot/${BOOTLOADER} of="${NAME}" conv=fsync,notrunc bs=512 skip=1 seek=1
fi

pigz -9 ${NAME}
sha256sum ${NAME}.gz > ${NAME}.gz.sha256

mkdir targets &>/dev/null
mv ${NAME}.gz targets/${NAME}.gz
mv ${NAME}.gz.sha256 targets/${NAME}.gz.sha256

exit 0
